cofacts/rumors-api

- src/index.js
fix for #15 
Enlarge formLimit from 56kb to 1mb and jsonLimit from 1mb to 10mb
Actually, koa-body doesn't take "textLimit" option. But readme has this option so I use it.
https://github.com/koajs/bodyparser/search?utf8=%E2%9C%93&q=textLimit
> Enlarge body size limit of koa-bodyparser fix #15

- src/graphql/queries/Search.js
#7 
需搭配 MrOrz/rumors-db#5 使用。
跑 `validate:sameDoc` 的結果:
```
---- Summary ----
110/124 correct
88.71 % correct.
```
看似跟調整前差不多，但我稍微檢查過，
`WRONG DOC` 和 `NOT FOUND` 幾乎都是找到重複或相似的謠言，
相信這個修改的實際效果應該會不錯。
> Use more_like_this query

- src/graphql/queries/Search.js
在 shard 為 1 的情況下 (#24)
False Negative 為 94.03%
False Positive 為 97.36%
其中 False Negative 很多還是相似文章造成的，
建議可以把 `theBestDoc` 移除。
> Add minimum_should_match to more_like_this query

- src/graphql/models/Article.js
- src/graphql/models/ReplyConnection.js
- src/graphql/queries/__fixtures__/GetReplyAndArticle.js
- src/graphql/queries/__tests__/GetReplyAndGetArticle.js
- src/graphql/queries/__tests__/__snapshots__/GetReplyAndGetArticle.js.snap
Sorts article's replyConnection by createdAt field by default, required by cofacts/rumors-site#29
Also provide necessary fields so that clients can sort by themselves.
> Adds field createdAt and updatedAt to ReplyConnection

- src/graphql/models/Article.js
- src/graphql/models/Reply.js
- src/graphql/queries/__fixtures__/GetReplyAndArticle.js
- src/graphql/queries/__tests__/GetReplyAndGetArticle.js
- src/graphql/queries/__tests__/__snapshots__/GetReplyAndGetArticle.js.snap
- src/graphql/util.js
Currently `Article`'s `replyconnection` field accepts "status" argument to return only deleted or not deleted replyconnections.
This PR makes `Reply` also support so.
> Add status filter to reply object type’s replyconnection field

- src/graphql/queries/ListReplies.js
- src/graphql/queries/__tests__/ListReplies.js
- src/graphql/queries/__tests__/__snapshots__/ListReplies.js.snap
The current error message is not informative when an user is not logged in and selfOnly is specified.
This PR gives clear error message for such situation.
> selfOnly should be preserved for logged-in users

- src/graphql/mutations/CreateArticle.js
- src/graphql/mutations/__fixtures__/CreateArticle.js
- src/graphql/mutations/__tests__/CreateArticle.js
- src/graphql/mutations/__tests__/__snapshots__/CreateArticle.js.snap
This prevents duplicate articles being sent into the database.
See https://github.com/cofacts/rumors-line-bot/issues/41 for the real-world cases we'd like to prevent.
Fixes #52 , https://github.com/cofacts/rumors-line-bot/issues/41
> Check duplications before creating new article on CreateArticle API

- src/auth.js
fixed #59 
github Public profile's name field is default null.
So if profile.displayName is null, use profile.username as name.
> Fixed some usernames are empty

- src/graphql/queries/ListArticles.js
- src/graphql/queries/__fixtures__/ListArticles.js
- src/graphql/queries/__tests__/ListArticles.js
- src/graphql/queries/__tests__/__snapshots__/ListArticles.js.snap
This PR enables `ListArticles` to show only articles by a specified author.
For spec please see #65 .
Fixes #65
> Add author related filter input for ListArticles

- src/graphql/models/Article.js
- src/graphql/models/FeedbackVote.js
- src/graphql/models/ReplyRequest.js
- src/graphql/mutations/CreateArticle.js
- src/graphql/mutations/CreateOrUpdateArticleReplyFeedback.js
- src/graphql/mutations/CreateOrUpdateReplyRequestFeedback.js
- src/graphql/mutations/CreateReplyRequest.js
- src/graphql/mutations/__fixtures__/CreateOrUpdateReplyRequestFeedback.js
- src/graphql/mutations/__tests__/CreateArticle.js
- src/graphql/mutations/__tests__/CreateOrUpdateReplyRequestFeedback.js
- src/graphql/mutations/__tests__/CreateReplyRequest.js
- src/graphql/mutations/__tests__/__snapshots__/CreateArticle.js.snap
- src/graphql/mutations/__tests__/__snapshots__/CreateOrUpdateReplyRequestFeedback.js.snap
- src/graphql/mutations/__tests__/__snapshots__/CreateReplyRequest.js.snap
- src/graphql/queries/__fixtures__/GetReplyAndArticle.js
- src/graphql/queries/__tests__/GetReplyAndGetArticle.js
- src/graphql/queries/__tests__/__snapshots__/GetReplyAndGetArticle.js.snap
- src/graphql/schema.js
This PR:
- adds required arg `reason` to `CreateArticle`
- adds optional arg `reason` to `CreateReplyRequest`
- adds `reason` field to `ReplyRequest` object type
- adds `CreateOrUpdateReplyRequestFeedback`, which allows editors to vote on the usefulness of reply request reasons
Related DB schema change: https://github.com/cofacts/rumors-db/pull/13
Fixes #67 
rumors-line-bot should provide `reason` when submitting articles, or submissions will fail.
> Add reason field to ReplyRequests

- src/graphql/models/Article.js
- src/graphql/mutations/__tests__/CreateArticle.js
- src/graphql/mutations/__tests__/CreateReply.js
- src/graphql/mutations/__tests__/__snapshots__/CreateArticle.js.snap
- src/graphql/mutations/__tests__/__snapshots__/CreateReply.js.snap
- src/graphql/queries/ListArticles.js
- src/graphql/queries/__tests__/ListArticles.js
- src/graphql/queries/__tests__/ListReplies.js
- src/graphql/queries/__tests__/__snapshots__/GetReplyAndGetArticle.js.snap
- src/graphql/queries/__tests__/__snapshots__/ListArticles.js.snap
- src/graphql/queries/__tests__/__snapshots__/ListReplies.js.snap
- src/graphql/util.js
#92.
We're using _id (`<id>`) instead of _uid (`<type>#<id>`) for sorting, so the cursors are also changed.
One thing that I don't understand is in `/src/util/client.js` at line 22, you used `sort` as the cursor. Why don't you use `id`?
> #92: deprecated api

- src/graphql/dataLoaders/urlLoaderFactory.js
- src/graphql/mutations/CreateArticle.js
- src/graphql/mutations/__fixtures__/CreateArticle.js
- src/graphql/mutations/__tests__/CreateArticle.js
- src/graphql/mutations/__tests__/__snapshots__/CreateArticle.js.snap
- src/util/__tests__/__snapshots__/scrapUrls.js.snap
- src/util/scrapUrls.js
This PR makes sure `CreateArticle` calls would invoke `scrapUrls` over the submitted text so that all the URLs in the submitted messages can be scrapped, also fills in its `hyperlinks` field for future searches.
Related to #41 
- Add `scrapUrls` to `CreateArticle` to fill `hyperlinks` field
- Remove unnecessary `cacheKeyFn` from `urlLoaderFactory` because URL strings are already serializable
- Alter `scrapUrls` so that the returned `url` in `ScrapResult` always matches the one in input text
> Scrap URLs when articles are submitted

- src/graphql/mutations/CreateReply.js
- src/graphql/mutations/__fixtures__/CreateReply.js
- src/graphql/mutations/__tests__/__snapshots__/CreateReply.js.snap
CreateReply now also scraps URL in its text & references.
Related to #41, should be symmetrical with #97
> Scrap URLs when replies are submitted

- src/graphql/models/Hyperlink.js
- src/graphql/queries/__fixtures__/ListArticles.js
- src/graphql/queries/__tests__/ListArticles.js
- src/graphql/queries/__tests__/__snapshots__/ListArticles.js.snap
This PR adds more field to `Hyperlink` object type by loading related field from `urls` index via dataloader.
Related to cofacts/rumors-site#102.
> More fields to Hyperlink object type

- src/graphql/queries/ListArticles.js
- src/graphql/queries/ListReplies.js
- src/graphql/queries/__fixtures__/ListReplies.js
- src/graphql/queries/__tests__/ListArticles.js
- src/graphql/queries/__tests__/ListReplies.js
- src/graphql/queries/__tests__/__snapshots__/ListArticles.js.snap
- src/graphql/queries/__tests__/__snapshots__/ListReplies.js.snap
Although we have url preview implemented, it seems that searching text does not match the title and content in URL previews.
This is because `ListArticles` are implemented incorrectly.
This PR fixes the problem by always including `'hyperlinks.title` and `hyperlinks.summary` in the searched fields.
This PR also makes `ListReplies`'s `moreLikeThis` filter searches `hyperlinks` as well. Its implementation was omitted before.
> should also look up moreLikeThis text in hyperlinks

- src/graphql/queries/ListArticles.js
- src/graphql/queries/ListReplies.js
- src/graphql/queries/__tests__/ListArticles.js
- src/graphql/queries/__tests__/ListReplies.js
- src/graphql/queries/__tests__/__snapshots__/ListArticles.js.snap
- src/graphql/queries/__tests__/__snapshots__/ListReplies.js.snap
Currently when `more_like_this` is used with other `filters`, the total count of the result would be the total number of items matching the filter, regardless of whether there is a match with `more_like_this`.
Actually it's a [document feature in `bool` query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html) that allows no items in `should` clause to be included in the result:
> If the bool query is in a query context and has a must or filter clause then a document will match the bool query even if none of the should queries match.
This PR adds `minimum_should_match` to bool query so that the `more_like_this` query in `should` clause can take effect of filtering unmatched items.
Fixes #110
> Fix total count issue by ensuring the more_like_this also filters out non-matching items.

- src/graphql/queries/ListArticles.js
- src/graphql/queries/ListReplies.js
Fixes #113 .
When searching, we should take URLs into account, i.e. put url search in the `should` queries.
This way articles with the same URL will be matched and will have higher score.
Thanks @linekin for the idea!!
> When listing articles & replies, take urls into account

- README.md
- src/scripts/__fixtures__/cleanupUrls.js
- src/scripts/__tests__/__snapshots__/cleanupUrls.js.snap
- src/scripts/__tests__/cleanupUrls.js
- src/scripts/cleanupUrls.js
Fixes #119 .
It does a sweep & update / delete operation on all urls that are both
1. not scanned before.
2. more than 1 day old
Outputs are like:
When most of the urls are referenced, writing `isReferenced: true`:
When most of the urls are deleted:
Note that although we are not adding `isReferenced` explicitly to the index mapping, the elasticsearch can refer to the correct mapping type after execution:
```
~/workspace/rumors-api ➠ curl localhost:62222/urls?pretty=true
{
"urls_v1_0_2" : {
"aliases" : {
"urls" : { }
},
"mappings" : {
"doc" : {
"properties" : {
"isReferenced" : {
"type" : "boolean"
},
```
> Script that clean up urls index

- src/graphql/queries/ListArticles.js
- src/graphql/queries/ListReplies.js
The recent occurence of LINE bot shows that ListArticle API sometimes failed to properly scrap URLs.
https://rollbar.com/mrorz/rumors-line-bot/items/19/
https://rollbar.com/mrorz/rumors-line-bot/items/151/
It causes:
```
[{"path": ["ListArticles"], "message": "Cannot destructure property `title` of 'undefined' or 'null'.", "extensions": {"code": "INTERNAL_SERVER_ERROR"}, "locations": [{"column": 7, "line": 3}], "authError": false}]
```
Then in term cuases:
```
TypeError: Cannot read property 'edges' of null (Most recent call first)
ListArticles.edges.length
```
However, scrapping should not interfere with ordinary searches. This PR filters out failed scrap results to fix the problem.
Related: https://github.com/cofacts/rumors-line-bot/issues/10
> Skip invalid scrapResults

- src/graphql/models/ArticleReply.js
- src/graphql/models/ReplyRequest.js
- src/graphql/mutations/CreateOrUpdateArticleReplyFeedback.js
- src/graphql/mutations/CreateOrUpdateReplyRequestFeedback.js
- src/graphql/mutations/__tests__/CreateOrUpdateArticleReplyFeedback.js
- src/graphql/mutations/__tests__/CreateOrUpdateReplyRequestFeedback.js
- src/graphql/mutations/__tests__/__snapshots__/CreateOrUpdateArticleReplyFeedback.js.snap
- src/graphql/mutations/__tests__/__snapshots__/CreateOrUpdateReplyRequestFeedback.js.snap
- `CreateOrUpdateReplyRequestFeedback` returns the target `ReplyRequest`
- `CreateOrUpdateArticleReplyFeedback` returns the target `ArticleReply`
The two API's original object type is a subset of `ReplyRequest` and `ArticleReply`, thus this PR does not introduce any breaking change.
In addition, this PR adds `ownVote` to `ReplyRequest` and `ArticleReply` so that API user can get the feedback of current user easily. It's used in [rumors-site](https://github.com/cofacts/rumors-site/blob/master/ducks/articleDetail.js#L297) as well.
> Create or update feedback should return the entity with its feedback updated

- src/graphql/mutations/CreateOrUpdateReplyRequestFeedback.js
- src/graphql/mutations/__tests__/CreateOrUpdateArticleReplyFeedback.js
- src/graphql/mutations/__tests__/CreateOrUpdateReplyRequest.js
- src/graphql/mutations/__tests__/CreateOrUpdateReplyRequestFeedback.js
- src/graphql/mutations/__tests__/__snapshots__/CreateOrUpdateArticleReplyFeedback.js.snap
- src/graphql/mutations/__tests__/__snapshots__/CreateOrUpdateReplyRequest.js.snap
- src/graphql/mutations/__tests__/__snapshots__/CreateOrUpdateReplyRequestFeedback.js.snap
Currently `CreateOrUpdateReplyRequestFeedback` does not properly return the id of updated `ReplyRequest`. This PR adds the missing ID and adds test cases around all `CreateOrUpdate*` APIs to make sure that IDs are properly filled.
> Make sure CreateOrUpdate* APIs have ids correctly set in its result

- src/graphql/mutations/UpdateArticleReplyStatus.js
- src/graphql/mutations/__tests__/UpdateArticleReplyStatus.js
- src/graphql/mutations/__tests__/__snapshots__/UpdateArticleReplyStatus.js.snap
Previously `UpdateArticleReplyStatus` will return `null` for `ArticleReply`, which is wrong. This PR fixes the bug so that apollo-client works better.
> UpdateArticleReplyStatus should returns articleId correctly

- src/util/__tests__/scrapUrls.js
- src/util/scrapUrls.js
gRPC calls will return out-of-order URL fetch results. This PR reorders the result from gRPC call using original URL order.
We first modify the unit test to create a failing test case:
We can see that in the snapshot, fetch result of `http://example.com/not-found` was added to the entry for `http://example.com/index.html`, which reproduces the bug in #139.
After the implementation:
This fixes #139.
> Reorders result from gRPC to fulfill rule of Dataloader

- src/graphql/mutations/CreateArticle.js
- src/graphql/mutations/__tests__/__snapshots__/CreateArticle.js.snap
A typo is identified, which adds a useless field `normalArticleReplycount` to each `article` document. This PR sets the field correctly.
> Fix typo in article creation API

- .travis.yml
- package.json
- src/graphql/models/Reply.js
- src/graphql/mutations/CreateReply.js
- src/graphql/mutations/__tests__/CreateReply.js
- src/graphql/mutations/__tests__/__snapshots__/CreateReply.js.snap
- src/util/__mocks__/grpc.js
- test/util/delayForMs.js
- test/util/strings.js
As discussed in [20200212 meeting](https://g0v.hackmd.io/AwNFa7L1QKiBPziTtYva0A#CreateReply-%E4%B8%8D%E8%A6%81%E7%AD%89-url-resolving%EF%BC%8C%E6%9C%89%E6%99%82%E5%80%99%E9%82%84%E6%9C%83%E5%87%BA%E9%8C%AF), currently `CreateReply` API resolves after all URLs are resolved, which is error-prone and makes editors wait for a significant amount of time.
This PR allows users to skip resolution of hyperlinks by:
- Still executes hyperlink resolution, but skip waiting for the promise by default
- `hyperlinks` field in `Reply` doc is filled in after resolution. If no URLs, it will be filled in with empty array. UI can check `hyperlinks`'s type to determine if hyperlink resolution is finished.
Add custom timeout to `grpc` so that we can simulate asynchronous hyperlink resolution.
We need to check …
> [CreateReply] allow skipping hyperlink resolving

- src/graphql/models/Article.js
- src/graphql/queries/ListArticles.js
- src/graphql/queries/ListReplies.js
- src/graphql/util.js
Replaces `getOperatorAndOperand` & `script` queries with `getRangeFieldParamFromArithmeticExpression` and `range` queries for all filters involving "GT", "LT", "EQ".
Fixes #148 by picking up all arithmetic operations left out in previous PR (#154 )
> Use range query for all artihmetic filters

- src/graphql/__tests__/util.js
- src/graphql/util.js
Pushing #161 to staging yields the following error:
The query variable sent by UI is:
```
{filter: {replyRequestCount: {GT: 1}, replyCount: {EQ: 0}}, orderBy: [{lastRequestedAt: "DESC"}]}
```
Note that `EQ: 0` makes `EQ` falsy and `getRangeFieldParamFromArithmeticExpression` does not properly handle the case, generating `replyCount:  {eq: 0}` as a elasticsearch range query
This PR fixes `getRangeFieldParamFromArithmeticExpression` and adds unit test addressing `getRangeFieldParamFromArithmeticExpression`.
Notice that this does not overlap with existing API test, since the API test connects to DB, and the unit test included in this PR tests boundary conditions that is too trivial to prepare DB fixtures for an API test.
> Fix range query arithmetic operator bug

- package-lock.json
- package.json
- src/graphql/__tests__/util.js
- src/graphql/queries/ListArticles.js
- src/graphql/queries/__fixtures__/ListArticles.js
- src/graphql/queries/__tests__/ListArticles.js
- src/graphql/queries/__tests__/__snapshots__/ListArticles.js.snap
- src/graphql/util.js
This PR implements `hasArticleReplyWithMorePositiveFeedback` which:
1. When `true`, gives only the articles with at least 1 article reply whose `#(positive feedback) > #(negative feedback)`
2. When `false`, gives only the articles with no article reply, or all its article replies has `#(positive feedback) <= #(negative feedback)`
I found that `normalArticleReplyCount` in `ListArticles` fixture actually does not match `normalArticleReplyCount`. This PR adjusts `ListArticles` fixtures so that
- For all article fixtures, `normalArticleReplyCount` matches length of `articleReplies` array.
- Preserve some of articles that has no article replies
- Adds some deleted article replies, which should not affect any filter since they are deleted
- Fetches the field that is being sorted / filtered in …
> implements hasArticleReplyWithMorePositiveFeedback on ListArticles

- src/graphql/models/Article.js
- src/graphql/queries/__tests__/GetReplyAndGetArticle.js
- src/graphql/queries/__tests__/__snapshots__/GetReplyAndGetArticle.js.snap
Currently, `requestedForReply` of `Article` object type would throw error if the user is not logged-in. However, other fields that requires authentication (such as [`ownVote`](https://github.com/cofacts/rumors-api/blob/master/src/graphql/models/ArticleReply.js#L68-L89), [`canUpdateStatus`](https://github.com/cofacts/rumors-api/blob/master/src/graphql/models/ArticleReply.js#L42-L51)) just returns `null` if the user is not logged in.
`assertUser()` is meant for mutation resolvers and ordinary object type resolvers should avoid using `assertUser()`.
Related discussion: 
- https://g0v-tw.slack.com/archives/C2PPMRQGP/p1588665581350300
- https://g0v-slack-archive.g0v.ronny.tw/index/channel/C2PPMRQGP#ts-1588665581.350300
> requestedForReply should return null when not logged in

- src/graphql/models/Article.js
- src/graphql/mutations/__tests__/CreateReply.js
- src/graphql/queries/ListArticles.js
- src/graphql/queries/ListReplies.js
- src/graphql/queries/__tests__/__snapshots__/ListArticles.js.snap
- src/graphql/util.js
Previously, every arithmetic input (with `{LT, GT, ...}`) has its own input object type, but they are almost the same -- there are only 2 types of such input throughout `rumors-api`, one is for integers, another for date strings.
This PR replaces these `getArithmeticExpressionType` calls with 2 input object type instance to simplify the schema. Behavior of rumors-api should not be affected at all.
> [Refactor] remove duplicated input object types

- src/graphql/queries/ListReplies.js
- src/graphql/queries/__tests__/ListReplies.js
- src/graphql/queries/__tests__/__snapshots__/ListReplies.js.snap
[Reply page mockup](https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?node-id=299%3A403) requires a multi-select reply type filter for `ListReplies`.
This PR:
- implements `ListReplies`'s `types` filter.
- add snapshot names & fields under test to test cases that has multiple snapshot files so that it's easier to do code review.
> Add "types" filter for ListReplies

- src/graphql/queries/ListArticleReplyFeedbacks.js
- src/graphql/queries/__tests__/ListArticleReplyFeedbacks.js
- src/graphql/queries/__tests__/__snapshots__/ListArticleReplyFeedbacks.js.snap
Currently if we specify multiple filters to `ArticleReplyFeedback`, the search result will be the union of all filters:
1.
- Filter: `{createdAt: {GT: "2020-05-29T00:00:00Z"}}`
- Result `totalCount`: 26
2.
- Filter: `{createdAt: {GT: "2020-05-29T00:00:00Z"}, vote: UPVOTE}`
- Result`totalCount`: 145358
This PR changes the behavior to intersection so that the filter is more useful.
Originally the filters are attached to `shouldQueries`. However, we allow elasticsearch to include documents that matches only 1 should cause. `shouldQueries` should be only used in queries that involves relevance scoring, such as `more_like_this`.
Use `filterQueries` instead. All filters must match for elasticsearch to include a document.
> Multiple ArticleReplyFeedback filters should narrow down selection

- src/graphql/mutations/CreateArticleCategory.js
try to solve dynamic script compilation problem by using the same script in this mutation
related discussion:
reference:
https://stackoverflow.com/questions/60234600/too-many-dynamic-script-compilations-within-max-75-5m
> use parameter getter for createArticleCategory Mutation to avoid re-compilation

- src/auth.js
- src/checkHeaders.js
- src/index.js
Currently, rumors-api is designed to lock browser apps to a certain origin. This PR allows multiple origins can be allowed for one browser app.
- Currently we apply this to the only browser app, `RUMORS_SITE`, thus we handle `process.env.RUMORS_SITE_CORS_ORIGIN` exclusively. This is subject to change in future PRs when we introduce multiple apps, but the basic logic should be similar.
- The CORS origin setting is also used in login redirects, restricting browser to only redirect back to allowed origins. We made the following changes to the login redirect mechanism to support multiple domains:
1. Support comma separated `process.env.RUMORS_SITE_CORS_ORIGIN` string
2. Store which origin the user is from when login process is initiated. When redirecting back, first check if the origin is …
> Allow multiple origins for one appId

- src/graphql/queries/ListArticles.js
- src/graphql/queries/ListReplies.js
- src/graphql/queries/__fixtures__/ListArticles.js
- src/graphql/queries/__tests__/ListArticles.js
- src/graphql/queries/__tests__/ListReplies.js
- src/graphql/queries/__tests__/__snapshots__/ListArticles.js.snap
- src/graphql/queries/__tests__/__snapshots__/ListReplies.js.snap
Fixes #165 
- Implements `articleRepliesFrom` in #165 
- Drops `appId` because `userId` should be sufficient according to [`userId` / `appId` management proposal](https://g0v.hackmd.io/ZcoUOX_-RQSkJyl5xz4_Zg#%E6%96%B9%E5%90%91-2-%E9%87%9D%E5%B0%8D%E6%AF%8F%E5%80%8B-backend-user-%E9%83%BD%E7%94%A2%E7%94%9F%E4%B8%80%E5%80%8B-user-document)
- I cannot think of any useful use case filtering article-reply's `appId` yet
- Adds `userId` and `appId` to `ListReplies` filter, so that `ListArticles`, `ListReplies` filters work the same as `ListArticleReplyFeedbacks`'s.
- Removes the limitation that requires `userId` and `appId` must be specified together in `ListArticles` filter
- Previously we use `userId`-`appId` pair to identify users. However in the future [using only  `userId` should be …
> Implement articleRepliesFrom filter for ListArticles

- .env.sample
- src/checkHeaders.js
This is the temp solution for adding more app id (rumors-line-bot's LIFF).
Real solution will come in branch `create-user`; before that, let's just add another env var for the LINE bot.
Related code: https://github.com/cofacts/rumors-line-bot/blob/e75463b64cb4926b74f44a08e5b013a65c616c93/src/liff/lib.js#L178
> Add CORS origin for LINE bot LIFF

- src/graphql/models/Article.js
- src/graphql/queries/__fixtures__/GetReplyAndArticle.js
- src/graphql/queries/__tests__/GetReplyAndGetArticle.js
- src/graphql/queries/__tests__/__snapshots__/GetReplyAndGetArticle.js.snap
Allows more than 10 reply requests being loaded in `ArticleType`.
This fixes #164 
Note: In the unit test I added a new article, thus `scores` in snapshots changed.
> Load more reply request at once

- src/scripts/__tests__/__snapshots__/fetchStatsFromGA.js.snap
- Update `test/rumors-db` submodule revision to include `analytics` index settings (cofacts/rumors-db#45)
- Update unit test snapshot accordingly
- Mostly about index name change (alias --> real index name)
- Seems that elasticsearch is returning different order for indexes that has mappings. Not sure why, but I'll just accept that :P
> Update rumors-db with analytics index mappings

- README.md
- src/scripts/__tests__/__snapshots__/fetchStatsFromGA.js.snap
- src/scripts/__tests__/fetchStatsFromGA.js
- src/scripts/fetchStatsFromGA.js
- remove date validation to allow relative date pattern
- add useContentGroup option instead of guessing from start/end dates
note that functions in `util/date.js` are no longer referenced in the code base, but I'd like to keep them for now.
Will remove the file if they remain unused when the project is completed.
> modify command line options for fetchStatsFromGA script.

- .env.sample
- package-lock.json
- package.json
- src/index.js
This PR fixes #186 via:
- Upgrades koa and koa-session2 for `SameSite` support
- Turn on `samesite` and `secure` for session cookies
- If `secure` is not set, session cookies (`koa:sess` and `koa:sess.sig`) won't have Secure flag, and the browser does not apply SameSite=None
- Adds env var `COOKIE_SAMESITE_NONE` to toggle it. In some case `samesite` may be not required.
- Trust proxy headers
- This allows Koa to recognize `x-forwarded-proto` and send `secure: true` when calling `new Cookies()`.
- Related code analysis: https://github.com/koajs/koa/issues/974#issuecomment-307232498
- If `secure: true` is not set on `new Cookies()`, cookie middleware will throw exception saying that `secure` flag is only available under secure connections when we try to set a secure cookie.
- Add env var …
> Enable Samesite cookie on API server

- src/graphql/queries/ListArticles.js
- src/graphql/queries/__fixtures__/ListArticles.js
Currently `ListArticles(filter: {categoryId: [XXX]})` will include articles that has `XXX` even if
- `XXX` has been deleted from the article, or
-  `XXX` receives more negative feedback than positive.
This PR fixes the above scenario to make sure only `articleCategories` that is not deleted  yet and has positive (or neutral) feedback are considered.
> ListArticles categoryId filter fix

- package-lock.json
- package.json
- src/graphql/interfaces/Connection.js
- src/graphql/interfaces/Edge.js
- src/graphql/interfaces/Node.js
- src/graphql/interfaces/PageInfo.js
- src/graphql/models/Article.js
- src/graphql/models/ArticleCategory.js
- src/graphql/models/ArticleReplyFeedback.js
- src/graphql/models/Category.js
- src/graphql/models/Reply.js
- src/graphql/queries/__tests__/GetReplyAndGetArticle.js
- src/graphql/queries/__tests__/__snapshots__/GetReplyAndGetArticle.js.snap
- src/graphql/queries/__tests__/__snapshots__/ListArticles.js.snap
- src/graphql/util.js
- Create `Node`, `Edge`, `PageInfo` and `Connection` interfaces and have similar object types inherit from them.
- This helps components like `<LoadMore>` in rumors-site to create object-agnostic fragments that only retrieves common fields
- Also defines more strict `NonNull` and `ID` so that their type is more rigorous.
- When `resolveEdge` errors, the whole request (like `ListArticle`) would return `null` now, rather than return partially in the past. This makes more sense in terms of param error.
- Upgrade graphql-js to get better error message regarding interfaces. see graphql/graphql-js#2513
> Interface for connection related types

- src/graphql/dataLoaders/index.js
- src/graphql/dataLoaders/votedArticleReplyCountLoaderFactory.js
- src/graphql/dataLoaders/votedArticleReplyFeedbackCountLoaderFactory.js
- src/graphql/models/User.js
- src/graphql/queries/__fixtures__/GetUser.js
- src/graphql/queries/__tests__/GetUser.js
- src/graphql/queries/__tests__/__snapshots__/GetUser.js.snap
This PR is for fields required in Profile page UI.
- Figma: https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?node-id=912%3A385
- Spec: https://g0v.hackmd.io/bbreV0ZqRDarHl4Zt5UpEw
Detail
- Change `points` and `repliedArticleCount` from 'current-user only' to publicly available
- Add `votedArticleReplyCount` to `User`
- Add `GraphQLNonNull` when applicable
> Make profile page related fields in User object type publically available

- src/graphql/models/Article.js
- src/graphql/models/Reply.js
- src/graphql/models/__tests__/User.js
- src/graphql/queries/ListReplies.js
- src/graphql/queries/__fixtures__/GetReplyAndArticle.js
- src/graphql/queries/__tests__/GetReplyAndGetArticle.js
- src/graphql/queries/__tests__/__snapshots__/GetReplyAndGetArticle.js.snap
This PR adds `similarReplies` to `Reply` object type to display [similar reply section in reply page](https://www.figma.com/file/zpD45j8nqDB2XfA6m2QskO/Cofacts-website?node-id=894%3A85). Given that replies are often copied over to another, this function should be useful when finding duplicated replies.
Several refactors to `Article` object type's `relatedArticles` are also added, including:
- Default to sort by score (high to low)
- Add hyperlink title / summary matching
- Test highlights are generated in unit tests
> Similar replies API and revamp related artitle API

- README.md
- src/graphql/mutations/UpdateArticleReplyStatus.js
- src/scripts/__fixtures__/removeArticleReply.js
- src/scripts/__tests__/removeArticleReply.js
- src/scripts/removeArticleReply.js
Due to [recent spamming](https://www.facebook.com/groups/cofacts/permalink/2866149510283526/),
we are adding a script that:
- Marks an article-reply as deleted on user's behave
- Updates `normalArticleReplyCount`
The script is tested on staging.
> Script to remove an article reply on production

- src/graphql/models/User.js
In the user profile page for LINE bot users, I want to tell site visitors that this user is from LINE and its username / avatar is randomly generated. Therefore, I would like to expose user's `appId`.
Currently I cannot think of reasons why we kept it for current user. No concern is documented in [the design document](https://g0v.hackmd.io/ZcoUOX_-RQSkJyl5xz4_Zg#%E6%96%B9%E5%90%91-2-%E9%87%9D%E5%B0%8D%E6%AF%8F%E5%80%8B-backend-user-%E9%83%BD%E7%94%A2%E7%94%9F%E4%B8%80%E5%80%8B-user-document) either. This PR removes the restriction.
> [Trivial] expose user.appId for all users & all apps

- .env.sample
- src/auth.js
This PR fixes #250 
On Mac & iOS safari, users cannot login when they visit https://cofacts.org.
This is because the current login mechanism will write cookie to https://cofacts-api.g0v.tw.
Even though https://cofacts-api.g0v.tw have CORS enabled and also uses `sames-site: lax`, it is possibly that [browsers *are* blocking all third-party cookies](https://www.adexchanger.com/privacy/chrome-is-killing-cookies-but-samesite-still-needs-to-be-updated/) anyway. 
We redirect users to domains listed in `RUMORS_SITE_REDIRECT_ORIGIN`.
After we apply corresponding changes in rumors-deploy ( cofacts/rumors-deploy#18 ), we can always redirect users to `https://cofacts.tw` or `https://en.cofacts.tw`, depending on which site the user is visiting.
We also have better error handing for URL concatenation …
> Redirect user to domains in RUMORS_SITE_REDIRECT_ORIGIN to fix login issue

- src/graphql/models/SlugErrorEnum.js
- src/graphql/mutations/UpdateUser.js
- src/graphql/mutations/__tests__/__snapshots__/UpdateUser.js.snap
- src/graphql/queries/ValidateSlug.js
- src/graphql/queries/__fixtures__/ValidateSlug.js
- src/graphql/queries/__tests__/ValidateSlug.js
- src/graphql/schema.js
- src/util/user.js
This PR fixes #242 .
The definition of "invalid slug": matches any of the following
- empty, or contains just space
- has trailing or leading space
- contains URL components like `:` or `/`
- is already taken by another user
This PR
- adds a query API `ValidateSlug` for UI to check if a slug is valid
- blocks invalid slug in `UpdateUser`
> Validate slug and block invalid slug

- src/auth.js
FB Graph API v3.2 is going to be deprecated on May 04 2021. This PR upgrades Graph API we use to login users to the latest v10.0.
Doc: https://github.com/jaredhanson/passport-facebook/pull/234#issuecomment-456553856
After clicking "Facebook" login button, it's being redirected to `v10.0` endpoint before being shown a FB login screen.
Facebook reports that there will be no breaking change
> Use FB Graph API v10

- src/util/__fixtures__/user.js
- src/util/__tests__/__snapshots__/user.js.snap
- src/util/__tests__/user.js
- src/util/user.js
Issue: website users cannot submit reply requests in [release tests](https://g0v.hackmd.io/rf0A7MRfTOC613QZmFehQA#%E2%9B%94%EF%B8%8F-Release-Blockers).
Root cause: in #263 we use `user.id` and `user.appId` in GraphQL context instead of from GraphQL context, for several APIs including `CreateOrUpdateReplyRequest`.
However, website users actually do not have `user.appId`, as it is a new field.
This PR fixes the bug by making the utility function `createOrUpdateUser` always fill in `appId` for web users.
Note: this PR does not change the registration process via passport.js. Therefore, new website users still do not have `appId` in its `users` document as before.
> Fix web users cannot submit reply requests

- .github/workflows/ci.yml
- package-lock.json
- package.json
- src/scripts/migrations/createBackendUsers.js
- src/util/__fixtures__/getAllDocs.js
- src/util/__tests__/getAllDocs.js
- src/util/getAllDocs.js
We are introducing multiple scripts for [category review](https://g0v.hackmd.io/EcrdwfZrQOSTGX7yK6nn4w) & [user blocking mechanism](https://g0v.hackmd.io/rf0A7MRfTOC613QZmFehQA#User-Blocking) in future PRs (such as #265, #267).
This PR adds preparations for those scripts and is organized to a separate PR to make the size of future PRs more managable.
Added in this PR:
- Install `cli-progress` to display progress in cli scripts (actually used in PRs like #265, #267)
- Align github CI node version with the one in Dockerfile
- Extract `getAllDocs()` (an async generator to walk through all matching docs in an ES index) to a separate utility function
> Prepare utility for scripts

- README.md
- src/scripts/__fixtures__/blockUser.js
- src/scripts/__tests__/blockUser.js
- src/scripts/blockUser.js
Implements part of the blocking mechanism (ReplyRequest only) designed as the [2nd milestone in the User Blocking feature](https://g0v.hackmd.io/@mrorz/cofacts-meeting-notes/%2Frf0A7MRfTOC613QZmFehQA).
- A script, `blockUser`, is added to set blocked reason (expected to be an URL to an announcement) and changes the user's normal `replyRequest` status
- Update article's reply request count & last replied at using the remaining normal replyRequests
- The scripts can be executed multiple times in case of error
- It is tested using production snapshot data; did not encounter any error.
> Script that sets blockedReason and blocks reply rquests

- .env.sample
- README.md
- src/scripts/__fixtures__/genBERTInputArticles.js
- src/scripts/__tests__/genBERTInputArticles.js
- src/scripts/genBERTInputArticles.js
- src/util/pseudonymDict.js
This PR implements [script 2](https://g0v.hackmd.io/EcrdwfZrQOSTGX7yK6nn4w?view#Script-2-genBERTInputArticles-script-in-rumors-api) in category review.
- `$ node build/scripts/genBERTInputArticles.js -s <Google spreadsheet ID> -o <Output directory>`
- Validation part is skipped to save time :P
- Generates JSON files with articles that has article categories satisfying all of:
- created before `latestArticleCategoryCreatedAt` (sheet1 generation)
- positive feedback > negative feedback
- is not deleted nor blocked
Test run: around 10 minutes
> node_modules/.bin/babel-node -- src/scripts/genBERTInputArticles.js -s 1Y9FrI01in2hz5eiveGknH0HE081sr7gVuk0a7hqqKuc -o 20211128
> Writing feedbacks to database
> progress [========================================] 100% | ETA: 0s | 2989/2989
> 1418 …
> 2nd script of category review

- src/graphql/mutations/CreateOrUpdateArticleReplyFeedback.js
- src/scripts/__fixtures__/blockUser.js
- src/scripts/__tests__/blockUser.js
- src/scripts/blockUser.js
This implements [user blocking mechanism M4](https://g0v.hackmd.io/hk1v8Ka5TCmIZinQ6zKU9Q?view#M4-Block-all-contents-from-blocked-users-).
`blockUser` script now turns existing article-replies & article-reply feedbacks into blocked state as well.
Both article's reply count & article reply's feedback counts are also updated after putting these existing contents to `BLOCKED` state.
Refactor: extract `updateArticleReplyByFeedbacks` logic so that `blockUser` can reuse.
> Block user script processes comments & feedbacks

- src/graphql/queries/ListArticleReplyFeedbacks.js
- src/graphql/queries/ListArticles.js
- src/graphql/queries/ListReplies.js
- src/graphql/queries/ListReplyRequests.js
- src/graphql/queries/__tests__/ListReplyRequests.js
- src/graphql/queries/__tests__/__snapshots__/ListReplyRequests.js.snap
- src/graphql/util.js
- Introduce `ids` and `selfOnly` to `ListReplyRequests`, `ListArticles`, `ListReplies` and `ListReplyRequests`
- Implement utility `createCommonListFilter()` and `attachCommonListFilter()` as discussed in [3/30 meeting](https://g0v.hackmd.io/OdOwYeKjQsSyUVzuE-BGiw#%E9%80%81%E5%87%BA%E6%B5%81%E7%A8%8B%E6%94%B9%E7%89%88%E9%96%8B%E7%99%BC)
> List api enhancements

- package-lock.json
- package.json
- src/index.js
This PR introduces optional request logging (toggled by env var) to make debugging GraphQL requests easier.
- Add an additional env var `LOG_REQUESTS` that will output request info for each incoming request
- Turning this flag on will introduce lots of logs, needs to be aware of disk size when it is turned on
- When `LOG_REQUESTS` exists, it also shows incoming GraphQL request, variables, and resolved user info
- No change if `LOG_REQUESTS` do not exist in env var
> Install pino logger and add query logging plug-in

- src/graphql/mutations/CreateMediaArticle.js
- src/graphql/mutations/__tests__/CreateMediaArticle.js
- src/graphql/queries/ListArticles.js
- src/graphql/queries/__tests__/ListArticles.js
- src/graphql/util.js
- src/util/gcs.js
Current implementation of `CreateMediaArticle` will halt on file larger than a certain size.
It is halt because `await file.clone().buffer()` never resolves.
The root cause is that when we call `await file.clone().buffer()`, it reads the cloned stream and put its data in an internal buffer so that the original stream can still consume data afterwards. The read operation halts when the internal buffer is full.
Related issue:
- https://github.com/node-fetch/node-fetch/issues/151
- https://github.com/node-fetch/node-fetch/issues/665
In the current implementation we tried to use stream so that we don't need to load the entire file in memory nor in file system.
However, `image-hash` package requires a buffer as its input. Even if we provide a file path to it, it will read the entire file into …
> Use buffer instead of cloned stream

- src/graphql/models/Article.js
- src/graphql/queries/ListArticles.js
- src/graphql/queries/__fixtures__/GetReplyAndArticle.js
- src/graphql/queries/__tests__/GetReplyAndGetArticle.js
- src/graphql/queries/__tests__/ListArticles.js
- src/graphql/util.js
According to [meeting note](https://g0v.hackmd.io/_HXxDu6OQPaK08WFwOshtg#%E7%B0%A1%E5%8C%96%E4%BA%8C%E6%AC%A1%E8%A9%90%E9%A8%99%E5%85%AC%E5%91%8A%E6%B5%81%E7%A8%8B), it would be great to have an advanced filter for article replies to track down blocked user's activities. It would also help profile page, when listing replies of the current user.
This PR adds filters to the following fields:
- `Query.ListArticles`
- Adds `articleReply.appId / userId / createdAt / selfOnly` filter so that `ListArticles` returns only articles with article replies matching the specified filter.
- Adds `lastMatchingArticleReplyCreatedAt` sorts articles using the latest `articleReply`'s creation time matching the above filter
- `Article.articleReplies`
- Adds `appId`, `userId`, `selfOnly` filters to filter …
> Add articleReply filter to ListArticles

- src/graphql/models/ArticleReplyFeedback.js
- src/graphql/mutations/CreateOrUpdateArticleReplyFeedback.js
- src/graphql/mutations/__fixtures__/CreateOrUpdateArticleReplyFeedback.js
- src/graphql/mutations/__tests__/CreateOrUpdateArticleReplyFeedback.js
- src/graphql/queries/ListArticleReplyFeedbacks.js
- src/graphql/queries/__fixtures__/ListArticleReplyFeedbacks.js
- src/graphql/queries/__tests__/ListArticleReplyFeedbacks.js
- src/graphql/queries/__tests__/__snapshots__/ListArticleReplyFeedbacks.js.snap
Fixes #280 
- Update schema and expose `replyUserId`, `articleReplyUserId` for `ArticleReplyFeedback`
- `CreateOrUpdateArticleReplyFeedback` writes `replyUserId` and `articleReplyUserId` on creation
- `ListArticleReplyFeedback` can filter by `replyUserId`, `articleReplyUserId` or `authorId`
- `authorId`: lists feedbacks whose `replyUserId` is the specified ID, _or_ whose `articleReplyUserId` is the specified ID
- Migration script filling up `replyUserId` and `articleReplyUserId` for existing `ArticleReplyFeedback` (not checked in, just for copy & paste use)
> Record feedback target author and allow filtering by feedback authors

- src/graphql/models/Article.js
- src/graphql/mutations/CreateOrUpdateArticleReplyFeedback.js
- src/graphql/mutations/__fixtures__/CreateOrUpdateArticleReplyFeedback.js
- src/graphql/mutations/__tests__/CreateOrUpdateArticleReplyFeedback.js
- src/graphql/queries/__tests__/GetReplyAndGetArticle.js
- src/graphql/queries/__tests__/__snapshots__/GetReplyAndGetArticle.js.snap
The bug was introduced in #284 .
Querying `ArticleType`'s `attachmentUrl` will trigger `Cannot read properties of undefined (reading 'split')` error.
The root cause is that for non-image articles, `attachmentHash` is null. However, we send `null` to `MediaManager` to generate URL for `attachmentUrl` field.
This PR:
- Returns null for `attachmentUrl` if `attachmentHash` is null
- Introduces a test case that will fail if this PR is not implemented
In the image below, the article reply feedback for article `2889dua0k41ro` and reply `sKR1hn0BnX5-aOa4S29I` has its `articleReplyUserId` being `AWA_PbObyCdS-nWhukq-`; however, according to the article data, the article reply is actually created by user `AVqVwjqQyrDaTqlmmp_a`.
This PR
- Fixes the typo in the logic that wrongly grabs the first …
> Fix ArticleType's attachmentUrl and CreateOrUpdateArticleReplyFeedback's articleReplyUserId

- src/scripts/fetchStatsFromGA.js
When back filling old analytics data, we found that the fetched LIFF stats are inconsistent with the numbers on Google Analytics.
We can reproduce this on local machine, and found that the inaccuracy only happens when the data is sampled:
https://developers.google.com/analytics/devguides/reporting/core/v4/basics#sampling
If we specify a shorter date range when running the script, the inconsistency will be gone.
This PR adds a warning message when sampled data is detected from the Google Analytics Reporting API response.
Sampling should only happens when we manually back-fill the data. The hourly cron job should not have that much of data that triggers Google Analytics samplng.
> fetchStatsFromGA script now warns about sampled data

- package-lock.json
- package.json
- src/graphql/models/Article.js
- src/graphql/queries/__fixtures__/GetReplyAndArticle.js
- src/graphql/queries/__tests__/GetReplyAndGetArticle.js
- src/graphql/queries/__tests__/__snapshots__/GetReplyAndGetArticle.js.snap
This PR allows `Article`'s `relatedArticles` to find articles with similar media entry hash (`attachmentHash`).
So that even if image articles does not have any transcription, we can get similar articles by attachment hash:
Edge case: articles are generated back-to-back (within 1 second) so that hash are all the same
> Related media articles

- .env.sample
- src/graphql/queries/ListArticles.js
- src/graphql/queries/__tests__/ListArticles.js
- src/graphql/queries/__tests__/__snapshots__/ListArticles.js.snap
We are going to support all types of media by default, thus removing `MEDIA_ARTICLE_SUPPORT` env var and its related logic.
Also updates snapshot for ListArticle, including media articles in the snapshots of search results.
> Remove MEDIA_ARTICLE_SUPPORT env

- src/graphql/models/Article.js
- src/graphql/models/ArticleStatusEnum.js
- src/graphql/mutations/CreateArticle.js
- src/graphql/mutations/CreateMediaArticle.js
- src/graphql/mutations/__tests__/CreateMediaArticle.js
- src/graphql/mutations/__tests__/__snapshots__/CreateArticle.js.snap
- src/graphql/queries/ListArticles.js
- src/graphql/queries/__fixtures__/GetReplyAndArticle.js
- src/graphql/queries/__fixtures__/ListArticles.js
- src/graphql/queries/__tests__/GetReplyAndGetArticle.js
- src/graphql/queries/__tests__/ListArticles.js
- src/graphql/queries/__tests__/__snapshots__/GetReplyAndGetArticle.js.snap
- src/graphql/util.js
- Sync DB field
- Creation API `CreateArticle`, `CreateMediaArticle` writes to `status` field
- `ListArticles` adds `statuses` filter; do not list out `BLOCKED` articles by default
- `relatedArticles` in `Article` do not list out `BLOCKED` articles by default
- exception: for blocked articles, its `relatedArticles` will also include blocked articles
> Add status to article

- src/graphql/mutations/CreateArticle.js
- src/graphql/mutations/CreateMediaArticle.js
- src/graphql/mutations/__tests__/CreateArticle.js
- src/graphql/mutations/__tests__/CreateMediaArticle.js
In https://github.com/cofacts/rumors-api/pull/293 we introduced `status` field for `articles`, but we set all article's status to `NORMAL`.
In this PR, we apply changes similar to [other APIs](https://github.com/cofacts/rumors-api/commit/9e7c1497a594d4b3752c090a8c9cae04cf749706) to determine the default status of an article by if the user is blocked.
> Block new articles from blocked users

- src/graphql/queries/ListAIResponses.js
- src/graphql/queries/__fixtures__/ListAIResponses.js
- src/graphql/queries/__tests__/ListAIReponses.js
- src/graphql/queries/__tests__/ListAIResponses.js
- src/graphql/queries/__tests__/ListReplies.js
- src/graphql/queries/__tests__/__snapshots__/ListAIReponses.js.snap
- src/graphql/queries/__tests__/__snapshots__/ListAIResponses.js.snap
- src/graphql/queries/__tests__/__snapshots__/ListReplies.js.snap
- src/graphql/schema.js
- src/graphql/util.js
Implement `ListAIResponses` as planned in Phase 0: https://g0v.hackmd.io/@cofacts/rknFrmdk3#Phase-0-preparation
- Can filter by `createdAt`, `updatedAt`, `status`, `type`, etc.
- This PR also adds `userIds` to common filter, and add unit test
> Implement ListAIResponses

- src/scripts/genAIReply.js
Avoid sending extra args to OpenAI, which causes 400 error.
Note that if temperature is not given, `undefined` is used, and OpenAI will interprete that as default value (1) rather than 0.
> [genAIReply] Remove extra args that causes 400 when sending to OpenAI

- .env.sample
- src/index.js
This is part of the operation layer enhancement; see https://g0v.hackmd.io/luIa-z9HToC2zlFpD9yK3w#Op-%E5%88%86%E8%BA%AB%E5%B8%B3%E8%99%9F%E8%99%95%E7%90%86 .
Reorganize the logs in logging mechanism
- records HTTP header for GraphQL requests
- Also logs operation name, query, variables
- Enables tracking operations of a certain IP address
- Compact GraphQL logging
- Long strings are truncated with "..."
First log comes from GraphQL plugin. The next log comes from pino logger.
> feat: better organized request logs

- src/index.js
- Only record IP related header for easier user tracking
- headers makes ~70% of the log length
- other headers are already captured by pino
- remove spaces GraphQL query and reduce string length cap
- Removes variables from GraphQL to exclude sensitive data.
> feat: record less bytes in GraphQL request

- src/__tests__/__snapshots__/auth.js.snap
- src/graphql/dataLoaders/__tests__/__snapshots__/userLoaderFactory.js.snap
- src/graphql/models/Article.js
- src/graphql/models/__tests__/__snapshots__/User.js.snap
- src/graphql/queries/ListArticles.js
- src/graphql/queries/__tests__/ListArticles.js
- src/graphql/util.js
- src/scripts/__tests__/__snapshots__/cleanupUrls.js.snap
- src/util/__tests__/__snapshots__/scrapUrls.js.snap
- src/util/__tests__/__snapshots__/user.js.snap
- src/util/client.js
During development, we found that actually it is possible for pure text to have score > 100
In this PR, we expose MediaManager's similarity in the `edge` of `ListArticles`, so that clients like LINE bot don't need to rely on score to determine if there is a matching, similar image / video / etc file.
Refactors:
- [fix(graphql): default total count resolver should only use query in body](https://github.com/cofacts/rumors-api/commit/061daca53e00d12e519e1d2df6b73319527beb4f)
- Ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-count.html#search-count-request-body
- Also adds console.error that prints the whole error message to aid debugging
> [3] Expose media similarity in ListArticles

- src/graphql/models/Ydoc.js
- src/graphql/queries/__fixtures__/GetYdoc.js
The current implementation always gets `null` because it's reading the wrong field.
This PR fixes `GetYdoc` to read the correct field.
> Fix GetYdoc API

- .babelrc
- package-lock.json
- package.json
- src/util/__tests__/scrapUrls.js
- y.js's dependency, lib0, uses `exports` in `package.json` to differentiate files served for `import` and `require()`
- However, Jest < 28 does not support that, causing jest always loads lib0 in ESM format even when `require()` is used in yjs
- Ref: https://jestjs.io/blog/2022/04/25/jest-28#packagejson-exports
- `snapshotFormat` is set to minimize change impact, as Jest 29 changes the [default snapshot format](https://jestjs.io/blog/2022/08/25/jest-29)
- Add memory limit to avoid [heap space overflow](https://github.com/cofacts/rumors-api/actions/runs/6329608237/job/17190243479)
- Fix broken test
- Remove unused `babel-plugin-rewire`
> Upgrade jest to v29

- src/graphql/models/Article.js
- src/graphql/models/ArticleReference.js
- src/graphql/models/ArticleReply.js
- src/graphql/models/Reply.js
- src/graphql/util.js
Make GraphQL return types more strict so that clients can have less null checks.
Range: `Article`, `Reply`, `ArticleReply`
> refactor: add non-null to common types' fields

- src/graphql/models/Article.js
- src/graphql/models/ArticleReply.js
- src/graphql/models/Reply.js
In 2023/10/25 pre-release test, we found that there are some articles not clickable on staging.
GraphQL error shows that there are some article, article-reply and replies [have no `createdeAt`](https://g0v.hackmd.io/ZOZrbHxEQV25eP7a4dxzYw#%E6%9C%AA%E7%AB%9F%E9%A0%85%E7%9B%AE). However, we set `createdAt` as non-null back in https://github.com/cofacts/rumors-api/pull/320
This PR removes the non-null restriction on `createdAt` for articles, replies and article-replies.
> Nullable createdat

- Dockerfile
- src/graphql/mutations/CreateOrUpdateCooccurrence.js
- src/graphql/mutations/__tests__/CreateOrUpdateCooccurrence.js
- src/graphql/mutations/__tests__/__snapshots__/CreateOrUpdateCooccurrence.js.snap
Currently `CreateOrUpdateCooccurrence` will error if `id` is queried in the mutation.
The root cause is that `id` is not given in the resolver. We did not capture this error because we do not include `id` in test script.
This PR fixes the root cause and make sure it's tested properly.
Blocks https://github.com/cofacts/rumors-line-bot/pull/379 .
> fix(mutations): createOrUpdateCooccurrence should return id properly

- src/graphql/mutations/UpdateUser.js
Issue: https://github.com/cofacts/rumors-api/issues/257
> Allow empty slug when user update profile

- src/graphql/__tests__/util.js
- src/graphql/models/Article.js
- src/graphql/models/Contributor.js
- src/graphql/mutations/CreateArticle.js
- src/graphql/mutations/CreateMediaArticle.js
- src/graphql/mutations/__tests__/CreateMediaArticle.js
- src/graphql/mutations/__tests__/__snapshots__/CreateArticle.js.snap
- src/graphql/queries/ListArticles.js
- src/graphql/queries/__fixtures__/ListArticles.js
- src/graphql/queries/__tests__/ListArticles.js
- src/graphql/queries/__tests__/__snapshots__/ListArticles.js.snap
- src/graphql/util.js
- Added `contributors` as a nested object in article that includes following fields :
- https://github.com/cofacts/rumors-db/pull/67 
- `userId`
- `appId`
- `updatedAt`
- Added `article.transcribedAt` which returns the latest value of `contributors.updatedAt`
- ListArticles can filter by `contributors.userId`
Reference : https://g0v.hackmd.io/OhGIQzoxR5eF6audQuS_FQ#articles
Note: UserDB does not contain user: ai-transcript, so it returns null.
> Add article contributors

- .env.sample
- package-lock.json
- package.json
- src/graphql/mutations/CreateArticle.js
- src/graphql/mutations/CreateMediaArticle.js
- src/graphql/mutations/CreateReply.js
- src/graphql/mutations/__tests__/CreateArticle.js
- src/graphql/mutations/__tests__/CreateMediaArticle.js
- src/graphql/mutations/__tests__/CreateReply.js
- src/util/__tests__/archiveUrlsFromText.ts
- src/util/archiveUrlsFromText.ts
This PR fixes #136 .
We will use the Wayback Machine [Save Page Now API](https://docs.google.com/document/d/1Nsv52MvSjbLb2PCpHlat0gkzw0EvtSgpKHu4mk0MnrA/edit#heading=h.ssrtgctoluc9) to archive URLs extract from these content:
- article text
- article transcript text
- reply text
- reply reference
Refactor: use NodeJS typescript definition for NodeJS 18 (previously package-lock.json resolves to NodeJS 10's type and does not contain definition of new NodeJS APIs like `fetch`)
Submitting this to staging:
https://dev.cofacts.tw/article/2mpux6cst06ad
Triggers:
Job `spn2-c500e35508b30770bcc231501135d371eec369d5` result:
- `original_url`: `https://learningpa.cc/lp_form_v8/`
- Snapshot: https://web.archive.org/web/20240902074748/https://learningpa.cc/lp_form_v8/
- Screenshot: …
> Archive article and reply text to Wayback Machine

- src/graphql/queries/ListCooccurrences.js
- src/graphql/queries/__tests__/ListCooccurrences.js
- src/graphql/queries/__tests__/__snapshots__/ListCooccurrences.js.snap
When debugging cooccurrence issue, I found bug in `ListCooccurrences` API.
The API is almost just for debugging purpose, though.
- `minumim_should_match` on queries with no should query causes 0 result when filter is set
- remove unused sort-vote logic
> fix(graphql): ListCooccurrences API error

- src/graphql/mutations/CreateMediaArticle.js
So that the article can be searched right after insertion.
This is to fix the issue found during 20240916 test.
Analysis: https://g0v.hackmd.io/UHKMm7h_QIe5EB4Z0cGQ3g?view#nonumpa-%E7%9A%84-grouping-issue
LINE bot sending 4 images (2 new, 2 existing)
Cooccurrence can now be correctly grouped
> fix: add refresh when inserting media article

- src/graphql/models/Reply.js
- src/graphql/queries/__fixtures__/GetReplyAndArticle.js
- src/graphql/queries/__tests__/GetReplyAndGetArticle.js
- src/graphql/queries/__tests__/__snapshots__/GetReplyAndGetArticle.js.snap
> Add status field to Reply

- src/scripts/blockUser.ts
In previous PR #338 we added `await` to `yargs` in `blockUser` script. This is causing the following error when script is being executed:
> nodejs SyntaxError: await is only valid in async functions and the top level bodies of modules
The type of `yargs` is somehow `Sth | Promise<Sth>` hence the `await`. We try to use `Promise.resolve().then()` to tackle this.
> fix(scripts): fix top-level await issue

- Dockerfile
Currently Admin API cannot start on staging due to the fact that README is not included in docker.
This PR fixes the issue and makes API available on staging.
> [Trivial] fix(Dockerfile): copy adm/README as it is read in adm-api startup

- src/util/__tests__/archiveUrlsFromText.ts
- src/util/archiveUrlsFromText.ts
Recent Internet Archive is not working due to unexpected secret rotation.
We add logging so that this issue is easier to surface
> fix(archiveUrlsFromText): Improve logging for archived URLs with error handling

- src/graphql/util.js
The most recent model, `gemini-2.0-flash-001`, suffers from slow response issue, compared to its predecessor, the experimental `gemini-2.0-flash-exp`.
On the other hand, I found that `gemini-1.5-pro-002` in `asia-east1` (Taiwan) and `asia-northeast1` (Tokyo) is actually as fast as `gemini-2.0-flash-exp` on `us-cental1`, and its quality is also pretty good.
This PR sets up the LLM model settings for LLM transcript to prioritize `gemini-1.5-pro-002` in Asia, then  `gemini-2.0-flash-exp`. For now, we ignore the latest `gemini-2.0-flash-001` until it gets a significant speed boost.
> Adjust LLM parameters to speed things up

- src/adm/handlers/moderation/genAIReply.ts
- src/adm/handlers/moderation/replaceMedia.ts
- src/adm/index.ts
Implements Phase 1 moderation endpoints as described in the design document:
- Adds `/moderation/article/media` endpoint to replace article media using the `replaceMedia.js` script. 
- Adds `/moderation/aiReply` endpoint to regenerate AI replies using the `genAIReply.js` script. 
These endpoints complete the planned functionality for Phase 1 of the spam removal automation system.
**Related:**
- Design Doc: https://g0v.hackmd.io/@cofacts/HJlJCpfZA
> feat(admin): Implement moderation API endpoints for media and AI reply
