cofacts/rumors-api

src/graphql/queries/ListReplies.js, src/graphql/queries/SearchReplies.js, src/graphql/queries/__fixtures__/ListReplies.js, src/graphql/queries/__tests__/ListReplies.js, src/graphql/queries/__tests__/__snapshots__/ListReplies.js.snap, src/graphql/schema.js, test/util/GraphQL.js
The API allows people to
- Search for existing replies using keywords
- List user's own written replies
- Filter for certain type of replies
=> Adds reply listing API

src/graphql/models/ReplyConnection.js, src/graphql/mutations/UpdateReplyConnectionStatus.js, src/graphql/queries/__tests__/GetReplyAndGetArticle.js, src/graphql/queries/__tests__/__snapshots__/GetReplyAndGetArticle.js.snap
Adds a boolean field for replyconnection so that UI can know whether we should display delete / restore button
=> Add field “canUpdateStatus” in ReplyConnection

src/graphql/models/ReplyTypeEnum.js
=> Adds OPINIONATED to reply type enum.

src/graphql/models/Article.js, src/graphql/models/ReplyConnectionStatusEnum.js, src/graphql/mutations/UpdateReplyConnectionStatus.js, src/graphql/queries/__tests__/GetReplyAndGetArticle.js, src/graphql/queries/__tests__/__snapshots__/GetReplyAndGetArticle.js.snap
This is required to make https://github.com/cofacts/rumors-line-bot/issues/30 easy
=> Add “status” arg to replyConnection field of Article type

src/graphql/queries/__tests__/ListArticles.js, src/graphql/queries/__tests__/__snapshots__/ListArticles.js.snap, src/graphql/util.js
=> Asking pageInfo from empty list now does not error.

src/graphql/queries/ListArticles.js, src/graphql/queries/__tests__/ListArticles.js, src/graphql/queries/__tests__/__snapshots__/ListArticles.js.snap
=> Support replyRequestCount filter in ListArticles query

src/graphql/dataLoaders/index.js, src/graphql/dataLoaders/repliedArticleCountLoaderFactory.js, src/graphql/models/User.js, src/graphql/queries/__fixtures__/GetUser.js, src/graphql/queries/__tests__/GetUser.js, src/graphql/queries/__tests__/__snapshots__/GetUser.js.snap
Adds `repliedArticleCount` to current user field. Not part of public info.
Snapshot tests included, please see unit test.
Fixes #74
=> Add number of articles the user has replied in "user" object type

src/graphql/dataLoaders/index.js, src/graphql/dataLoaders/userLevelLoaderFactory.js, src/graphql/models/User.js, src/graphql/queries/__fixtures__/GetUser.js, src/graphql/queries/__tests__/GetUser.js, src/graphql/queries/__tests__/__snapshots__/GetUser.js.snap, src/util/__tests__/level.js, src/util/level.js
Calculates user's accumulated "points" and their level.
Fix #74
=> [Gamification] Add user level & points calculation logic

src/graphql/mutations/CreateOrUpdateArticleReplyFeedback.js, src/graphql/mutations/__tests__/CreateOrUpdateArticleReplyFeedback.js, src/graphql/mutations/__tests__/__snapshots__/CreateOrUpdateArticleReplyFeedback.js.snap
- added field comment for the api
- updated test snapshot
=> Issue #75: add comment for article reply feedback

src/auth.js
I am still working on Rollbar issue 58 & 44. 
But seeing the issue still occur in last 60 hours, and twitter developer account is a little bit hard to apply..
I think I should push Rollbar issue 59 fix first.
Fixes #93
=> Fix unauthorized bug on first login after signing up

src/graphql/dataLoaders/articleReplyFeedbacksLoaderFactory.js, src/graphql/mutations/__fixtures__/CreateOrUpdateArticleReplyFeedback.js, src/graphql/mutations/__tests__/__snapshots__/CreateOrUpdateArticleReplyFeedback.js.snap
=> Allow feedback count to be > 10

.travis.yml, src/graphql/models/Hyperlink.js, src/graphql/mutations/CreateArticle.js, src/graphql/mutations/CreateReply.js, src/graphql/mutations/__fixtures__/CreateReply.js, src/graphql/mutations/__tests__/__snapshots__/CreateArticle.js.snap, src/graphql/mutations/__tests__/__snapshots__/CreateReply.js.snap, src/graphql/queries/__fixtures__/ListArticles.js, src/graphql/queries/__fixtures__/ListReplies.js, src/util/__tests__/__snapshots__/scrapUrls.js.snap, src/util/__tests__/scrapUrls.js, src/util/scrapUrls.js
Added fbclid filter, remove fbclid in query parameter.
=> add fbclid filter funcation

README.md, docker-compose.yml
This PR updates README and `docker-compose.yml` so that it can `docker-compose up` without problem.
cc/ @yanglin5689446 currently if you `docker-compose up` you may encounter error about gRPC binaries. This PR should fix the issue.
=> Fix dev setup

README.md, src/graphql/queries/ListArticles.js, src/graphql/queries/__fixtures__/ListArticles.js, src/graphql/queries/__tests__/ListArticles.js, src/graphql/queries/__tests__/__snapshots__/ListArticles.js.snap
issue #141 
Add new sort option to `ListArticles` query that cant sort articles by the timestamp of the latest reply.
Also f05e962 fixes a small setup bug.
=> Add latest replied sort option

src/util/protobuf/resolve_error.proto
Reflect changes in https://github.com/cofacts/url-resolver/pull/70/files#diff-64ff70ff651c3a5a54fda110aa5fb88c
Should merge along with https://github.com/cofacts/url-resolver/pull/70/
=> [Trivial] Sync proto file with url-resolver

src/graphql/models/ArticleReply.js, src/graphql/queries/ListArticles.js, src/graphql/queries/__fixtures__/ListArticles.js, src/graphql/queries/__tests__/ListArticles.js, src/graphql/queries/__tests__/__snapshots__/ListArticles.js.snap
This PR adds `replyTypes` filter to `ListArticles` so that users can list articles with specified reply types.
=> [ListArticles] add reply type filter

README.md, src/scripts/__tests__/__snapshots__/fetchStatsFromGA.js.snap, src/scripts/__tests__/fetchStatsFromGA.js, src/scripts/fetchStatsFromGA.js
follow up PR for [stored script mechanism](https://github.com/cofacts/rumors-api/pull/188#discussion_r465199034) as discussed in #188
=> Load script

src/graphql/models/ReplyRequest.js, src/graphql/queries/ListReplyRequests.js, src/graphql/queries/__fixtures__/ListReplyRequests.js, src/graphql/queries/__tests__/ListReplyRequests.js, src/graphql/queries/__tests__/__snapshots__/ListReplyRequests.js.snap, src/graphql/schema.js
ListReplyRequest API
- pagination args: first, after, before
- filter args: userId, appId, articleId, createdAt
- orderBy args: createdAt, vote
=> List reply requests

src/graphql/mutations/UpdateUser.js, src/graphql/mutations/__tests__/UpdateUser.js, src/graphql/mutations/__tests__/__snapshots__/UpdateUser.js.snap, src/graphql/queries/__tests__/__snapshots__/GetUser.js.snap, src/util/__tests__/user.js, src/util/user.js
- change default image size to 100
- add image size to facebook url
- omit avatarData field on non-openpeeps updates, instead of wiping it
=> minor avatar related changes

src/graphql/queries/__tests__/__snapshots__/ListReplies.js.snap, src/scripts/migrations/createBackendUsers.js
=> Update rumors-db to latest

src/graphql/models/User.js, src/graphql/queries/ListBlockedUsers.js, src/graphql/queries/__fixtures__/ListBlockedUsers.js, src/graphql/queries/__tests__/ListBlockedUsers.js, src/graphql/queries/__tests__/__snapshots__/ListBlockedUsers.js.snap, src/graphql/schema.js
Corresponds to [2nd milestone](https://g0v.hackmd.io/rf0A7MRfTOC613QZmFehQA#2nd-milestone-blocking-mechanism) in user blocking mechanism
- Adds `blockedReason` field to `User` object type
- Necessary for website to determine if we should block an user
- `ListBlockedUsers` API
- So that we can list all blocked user & their blocked contents in milestone 3
=> Expose user blockage information

src/graphql/mutations/CreateArticleCategory.js, src/graphql/mutations/CreateOrUpdateArticleCategoryFeedback.js, src/scripts/__fixtures__/genCategoryReview.js, src/scripts/__tests__/genCategoryReview.js, src/scripts/genCategoryReview.js, src/scripts/migrations/__fixtures__/importFlowAnnotation.js, src/scripts/migrations/__tests__/importFlowAnnotation.js, src/scripts/migrations/importFlowAnnotation.js
Discussion: "若水 ground truth" in https://g0v.hackmd.io/@mrorz/cofacts-meeting-notes/%2FlYTN-n1xQyqlHB9oeaPvuQ
This PR implements migration script, `importFlowAnnotation.js`, that imports ground truth data from Flow annotators (https://github.com/cofacts/ground-truth/blob/main/20211204_14859.zip) to database by:
0. Map 0~16 (Flow's annotation) to actual category ID used in database
1. Create (or update) app user ID=`category-reviewer` and user ID=`flow-annotator` in `users` index
- `genCategoryReview` is also updated so that it will look for previous reviewer feedback using the ID in `users` index
2. add article category (using app `RUMORS_AI` and app user ID "flow-annotator") if the article category is not existed yet
- If there exists a deleted matching article category, the article …
=> Flow tag import script

.env.sample, src/graphql/queries/ListArticles.js, src/graphql/queries/__tests__/ListArticles.js, src/graphql/queries/__tests__/__snapshots__/ListArticles.js.snap
Add MEDIA_ARTICLE_SUPPORT env to switch default articleTypes filter as discuss in https://github.com/cofacts/rumors-site/pull/490
=> Add MEDIA_ARTICLE_SUPPORT env to switch default articleTypes filter

src/scripts/__fixtures__/blockUser.js, src/scripts/__tests__/blockUser.js, src/scripts/blockUser.js
Design doc:
https://g0v.hackmd.io/XBJS-KEtScWyVCuQ9P_iNQ#M2-Script-for-setting-article-status
This PR modifies block user script so that it can set spammer's article status to "blocked"
=> feat(blockUser): changes spammer's article status when blocking an user

README.md, ecosystem.config.js, src/scripts/replaceMedia.js
Ref: https://pm2.keymetrics.io/docs/usage/log-management/#disable-logging
Tested on staging - left: CloudWatch (docker logs still forwarded); right: log files are no longer created
=> Disable log files

package.json, src/graphql/models/Article.js, src/graphql/models/Cooccurrence.js, src/graphql/mutations/CreateOrUpdateCooccurrence.js, src/graphql/mutations/__fixtures__/CreateOrUpdateCooccurrence.js, src/graphql/mutations/__tests__/CreateOrUpdateCooccurrence.js, src/graphql/mutations/__tests__/__snapshots__/CreateOrUpdateCooccurrence.js.snap, src/graphql/queries/ListCooccurrences.js, src/graphql/queries/__fixtures__/ListArticles.js, src/graphql/queries/__fixtures__/ListCooccurrences.js, src/graphql/queries/__tests__/ListArticles.js, src/graphql/queries/__tests__/ListCooccurrences.js, src/graphql/queries/__tests__/__snapshots__/ListArticles.js.snap, src/graphql/queries/__tests__/__snapshots__/ListCooccurrences.js.snap, src/graphql/schema.js
https://g0v.hackmd.io/f_Ze19PhQuqx_fzOAOkohQ#DB
New mutation
* CreateOrUpdateCooccurrence
New query
* ListCooccurrences
New type
* Cooccurrence
* articles: [Article!]!
* articleIds
* createdAt
* updatedAt
New field
* Article
* cooccurences
=> Support cooccurrences

src/graphql/mutations/CreateAIReply.js, src/graphql/util.js
Refactors
- Extract AI response creation & retrieval logic from `CreateAIReply`
- This will be reused in `ListArticles`, as it looks up transcripts and potentially creates one as AI replies.
- `createAIResponse` creates an AI response in loading state and returns a callback . When transcript is done, calls the provided callback to update the AI response.
- `getAIResponse` will try waiting for a loading AI Response if one exists.
- [refactor(graphql): extract latest AI response retrieval logic to utility](https://github.com/cofacts/rumors-api/commit/a399bff231dfd6b9d1c835887cfdebdc5316246c)
- [refactor(CreateAIReply): extract AI Response creation and updating to util function](https://github.com/cofacts/rumors-api/commit/1501d53f31b1dbef390db481c93b8f2d26eaff74)
=> [1] Refactor AI response retrieval and creation

src/graphql/models/AIResponse.js, src/graphql/models/AIResponseTypeEnum.js, src/graphql/models/Article.js, src/graphql/queries/__fixtures__/GetReplyAndArticle.js, src/graphql/queries/__fixtures__/ListAIResponses.js, src/graphql/queries/__tests__/GetReplyAndGetArticle.js, src/graphql/queries/__tests__/ListAIResponses.js, src/graphql/queries/__tests__/__snapshots__/ListAIResponses.js.snap
- ListAIResponses can list out transcripts for debugging
- add `aiTranscripts` to `Article` type for debugging (currently not used in application)
=> [4] List transcripts in ListAIResponses for debugging purposes

package-lock.json, package.json, src/graphql/mutations/CreateMediaArticle.js, src/graphql/mutations/__fixtures__/CreateMediaArticle.js, src/graphql/mutations/__tests__/CreateMediaArticle.js
This PR includes minimal packages for writing prosemirror document state (wrapped in ydoc) to `ydocs` ES index.
=> Write AI transcript to articles and ydoc

src/graphql/util.js
In reality, even if a voice repeats a certain phrase multiple times, the probability (confidence) of speech recognition should not be the same.
However, for hallucinated text, sometimes the text and probability just repeats themselves. Example results: https://docs.google.com/spreadsheets/d/10xfkOZpGJ-9vIvoYziEkD1lZETWMbBLDT-NABdQ8H_g/edit#gid=0&range=32:34
By removing segments with the same text and probability, we can reduce the hallucination by around 50%.
We also correct the [Whisper prompt](https://platform.openai.com/docs/guides/speech-to-text/prompting). Whisper, unlike ChatGPT, is _not_ instruction tuned. It is meaningless to provide commands inside its prompt. Therefore, we just include the bare minimum text to lead the transcript to use Taiwanese Mandarin (ex: 網際網路 instead of …
=> feat(graphql): remove apparent hallucination

src/scripts/__tests__/removeArticleReply.js, src/scripts/removeArticleReply.js
- https://github.com/cofacts/rumors-api/issues/258
- add replacedText param to replace spammer's reply
=> feat: add replacedText param for spammer's reply replacement

src/auth.js
=> Update FB graph API to v19

.babelrc, .env.sample, .eslintrc.js, .github/workflows/ci.yml, Dockerfile, README.md, ecosystem.config.js, package-lock.json, package.json, process-dev.json, src/commandListener.ts, tsconfig.json
Ref: https://github.com/cofacts/rumors-line-bot/pull/346
Try to introduce Typescript so that we can use Typescript to write future scripts
=> Add Typescript support

Dockerfile, src/index.js, static/graphiql.html
use [graphiql-cdn](https://github.com/graphql/graphiql/blob/main/examples/graphiql-cdn/index.html)
=> GraphQL Playground is currently not maintained; use GraphiQL instead

.github/workflows/build-and-push.yml, .github/workflows/ci.yml
Ref: https://github.com/cofacts/rumors-site/pull/602
=> Fix CI cache issue

.github/workflows/claude.yml
Message from Jules:
I've just added the Claude Code Action workflow to your repository.
To do this, I created a new GitHub Actions workflow file at `.github/workflows/claude.yml`. This new workflow enables the Claude PR Assistant, which you can trigger by mentioning "@claude" in issues and pull requests.
I configured the action to use Google Vertex AI as the backend, authenticating via OIDC with your existing GCP secrets (`GC_WORKLOAD_IDENTITY_PROVIDER` and `GC_SERVICE_ACCOUNT`). This setup follows the recommended practice from the official claude-code-action documentation.
=> Adding Claude Code Action
